### ISSUE TITLE
Deconstruct charge pad

### ISSUE THREAD

**Issue by s-lindenau** [GTX2GvO/wireless_charging#2]
When deconstructing a charge pad (by hand or deconstruct blueprint), the hidden accumulator + indicator fluidbox remain in the game. These should be destroyed on deconstruct.

**Comment by GTX2GvO** [comment]
Noticed in main.lua on line 326 it states "on_preplayer_mined_item".
Should be "on_pre_player_mined_item".

Was one of the things I noticed in control.lua before you joined. Guess I didn't check beyond that for any instances. 
Was changed between Factorio 0.15 and 0.16.
Should hopefully fix both player decon issues.

**Comment by s-lindenau** [comment]
Works very well now!
Will close this issue after multiplayer testing confirms everything is OK.

**Comment by s-lindenau** [comment]
Fixed in 0.17.5
