### ISSUE TITLE
indicator_tick: API call on invalid LuaEquipmentGrid

### ISSUE THREAD

**Issue by s-lindenau** [GTX2GvO/wireless_charging#9]
1295.730 Error MainLoop.cpp:1128: Exception at tick 74414: The mod Wireless Charging caused a non-recoverable error.
Please report this error to the mod author.

Error while running event wireless-charging_v17::on_tick (ID 0)
LuaEquipmentGrid API call when LuaEquipmentGrid was invalid.
stack traceback:
	__wireless-charging_v17__/src/main.lua:105: in function 'indicator_tick'
	__wireless-charging_v17__/src/main.lua:337: in function <__wireless-charging_v17__/src/main.lua:336>
stack traceback:
	[C]: in function '__index'
	__wireless-charging_v17__/src/main.lua:105: in function 'indicator_tick'
	__wireless-charging_v17__/src/main.lua:337: in function <__wireless-charging_v17__/src/main.lua:336
1295.730 Error ServerMultiplayerManager.cpp:92: MultiplayerManager failed: "The mod Wireless Charging caused a non-recoverable error.
Please report this error to the mod author.

Error while running event wireless-charging_v17::on_tick (ID 0)
LuaEquipmentGrid API call when LuaEquipmentGrid was invalid.
stack traceback:
	__wireless-charging_v17__/src/main.lua:105: in function 'indicator_tick'
	__wireless-charging_v17__/src/main.lua:337: in function <__wireless-charging_v17__/src/main.lua:336>
stack traceback:
	[C]: in function '__index'
	__wireless-charging_v17__/src/main.lua:105: in function 'indicator_tick'
	__wireless-charging_v17__/src/main.lua:337: in function <__wireless-charging_v17__/src/main.lua:336>

**Comment by s-lindenau** [comment]
Reproduction: deconstruct a vehicle (from Electric Vehicles Reborn) while it is getting charged on a rail.

**Comment by DasIstVoltone** [comment]
Error while running event wireless-charging-lib_v17::on_player_placed_equipment (ID 38)
LuaEntity API call when LuaEntity was invalid.
stack traceback:
	__wireless-charging-lib_v17__/src/main.lua:218: in function 'update_equipment'
	__wireless-charging-lib_v17__/src/main.lua:555: in function <__wireless-charging-lib_v17__/src/main.lua:552>
stack traceback:
	[C]: in function '__index'
	__wireless-charging-lib_v17__/src/main.lua:218: in function 'update_equipment'
	__wireless-charging-lib_v17__/src/main.lua:555: in function <__wireless-charging-lib_v17__/src/main.lua:552>

**Comment by s-lindenau** [comment]
Hi @DasIstVoltone 
Do you know what steps caused this issue for you?
SP or MP game?
Adding equipment to a (Power)Suit or Vehicle?

Note: stack is the same as issue #8

**Comment by DasIstVoltone** [comment]
Привет @s-lindenau 
In this case, I was sitting in the car, put the equipment in the car.

**Comment by s-lindenau** [comment]
Added a check if entities are valid in the next release. We probably need a new function to periodically cleanup any invalid items in our charge list: global.charging_accumulator_grids (or debug why invalid items are not removed on deconstruct)

**Comment by s-lindenau** [comment]
@DasIstVoltone This issue should be fixed in the latest release; 0.17.5 and lib 0.17.4.
Please try again. If you encounter any problems, feel free to log a new issue.
